<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KuponTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('kupon')->insert([
            'id' => '19',
            'userid' => '101',
            'ad' => 'Samat932',
            'miktar' => '10',
            'oran' => '1.97',
            'tarih' => '2025-07-07 13:41:28',
            'durum' => '0',
            'sil' => '0',
            'kesim' => '0',
            'odeme' => '19.7',
            'iptal' => '0',
            'ip' => '::1',
            'odendi' => '0',
            'canli' => '0',
            'sonmactarih' => '0',
            'toplam' => '1',
            'kazanan' => '0',
            'skontrol' => '0',
            'bonus' => '0',
            'numara' => null,
        ]);
        DB::table('kupon')->insert([
            'id' => '26',
            'userid' => '101',
            'ad' => 'Samat932',
            'miktar' => '10',
            'oran' => '1.33',
            'tarih' => '2025-07-07 18:21:24',
            'durum' => '0',
            'sil' => '0',
            'kesim' => '0',
            'odeme' => '13.3',
            'iptal' => '0',
            'ip' => '::1',
            'odendi' => '0',
            'canli' => '1',
            'sonmactarih' => '0',
            'toplam' => '1',
            'kazanan' => '0',
            'skontrol' => '0',
            'bonus' => '0',
            'numara' => null,
        ]);
        DB::table('kupon')->insert([
            'id' => '27',
            'userid' => '101',
            'ad' => 'Samat932',
            'miktar' => '10',
            'oran' => '1.32',
            'tarih' => '2025-07-07 18:22:38',
            'durum' => '0',
            'sil' => '0',
            'kesim' => '0',
            'odeme' => '13.2',
            'iptal' => '0',
            'ip' => '::1',
            'odendi' => '0',
            'canli' => '1',
            'sonmactarih' => '0',
            'toplam' => '1',
            'kazanan' => '0',
            'skontrol' => '0',
            'bonus' => '0',
            'numara' => null,
        ]);
        DB::table('kupon')->insert([
            'id' => '28',
            'userid' => '101',
            'ad' => 'Samat932',
            'miktar' => '10',
            'oran' => '1.37',
            'tarih' => '2025-07-07 18:25:05',
            'durum' => '0',
            'sil' => '0',
            'kesim' => '0',
            'odeme' => '13.7',
            'iptal' => '0',
            'ip' => '::1',
            'odendi' => '0',
            'canli' => '1',
            'sonmactarih' => '0',
            'toplam' => '1',
            'kazanan' => '0',
            'skontrol' => '0',
            'bonus' => '0',
            'numara' => null,
        ]);
        DB::table('kupon')->insert([
            'id' => '31',
            'userid' => '101',
            'ad' => 'Samat932',
            'miktar' => '10',
            'oran' => '5',
            'tarih' => '2025-07-07 18:33:51',
            'durum' => '0',
            'sil' => '0',
            'kesim' => '0',
            'odeme' => '50',
            'iptal' => '0',
            'ip' => '::1',
            'odendi' => '0',
            'canli' => '1',
            'sonmactarih' => '0',
            'toplam' => '1',
            'kazanan' => '0',
            'skontrol' => '0',
            'bonus' => '0',
            'numara' => null,
        ]);
        DB::table('kupon')->insert([
            'id' => '32',
            'userid' => '101',
            'ad' => 'Samat932',
            'miktar' => '10',
            'oran' => '1.14',
            'tarih' => '2025-07-08 01:07:03',
            'durum' => '0',
            'sil' => '0',
            'kesim' => '0',
            'odeme' => '11.4',
            'iptal' => '0',
            'ip' => '::1',
            'odendi' => '0',
            'canli' => '1',
            'sonmactarih' => '0',
            'toplam' => '1',
            'kazanan' => '0',
            'skontrol' => '0',
            'bonus' => '0',
            'numara' => null,
        ]);
        DB::table('kupon')->insert([
            'id' => '33',
            'userid' => '101',
            'ad' => 'Samat932',
            'miktar' => '10',
            'oran' => '6.5',
            'tarih' => '2025-07-08 01:09:13',
            'durum' => '0',
            'sil' => '0',
            'kesim' => '0',
            'odeme' => '65',
            'iptal' => '0',
            'ip' => '::1',
            'odendi' => '0',
            'canli' => '1',
            'sonmactarih' => '0',
            'toplam' => '1',
            'kazanan' => '0',
            'skontrol' => '0',
            'bonus' => '0',
            'numara' => null,
        ]);
        DB::table('kupon')->insert([
            'id' => '34',
            'userid' => '101',
            'ad' => 'Samat932',
            'miktar' => '10',
            'oran' => '2.12',
            'tarih' => '2025-07-08 01:23:57',
            'durum' => '0',
            'sil' => '0',
            'kesim' => '0',
            'odeme' => '21.2',
            'iptal' => '0',
            'ip' => '::1',
            'odendi' => '0',
            'canli' => '0',
            'sonmactarih' => '0',
            'toplam' => '1',
            'kazanan' => '0',
            'skontrol' => '0',
            'bonus' => '0',
            'numara' => null,
        ]);
        DB::table('kupon')->insert([
            'id' => '35',
            'userid' => '101',
            'ad' => 'Samat932',
            'miktar' => '10',
            'oran' => '3.65',
            'tarih' => '2025-07-08 01:34:22',
            'durum' => '0',
            'sil' => '0',
            'kesim' => '0',
            'odeme' => '36.5',
            'iptal' => '0',
            'ip' => '::1',
            'odendi' => '0',
            'canli' => '1',
            'sonmactarih' => '0',
            'toplam' => '1',
            'kazanan' => '0',
            'skontrol' => '0',
            'bonus' => '0',
            'numara' => null,
        ]);
    }
}
