<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KuponMacTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('kupon_mac')->insert([
            'id' => '30',
            'oranid' => null,
            'kuponid' => '31',
            'userid' => '101',
            'oran' => '5',
            'tur' => '-1.5 Hayırvak Djokovic',
            'macid' => '1928619',
            'sonuc' => '0',
            'tarih' => '2025-07-07 18:33:51',
            'canli' => '1',
            'session_id' => null,
            'canlidakika' => '128',
            'skor' => '0-0',
            'iptal' => null,
            'aciklamasi' => 'Set Handicap',
            'orangrup' => null,
            'evsahibi' => 'Alex De Minaur',
            'deplasman' => 'Novak Djokovic',
            'mackodu' => '1024226037',
            'sport_id' => '1',
            'matchdate' => '2025-07-07 15:32:00',
            'result' => '0',
            'canliskor' => '0-0',
            'botid' => '61449487',
        ]);
        DB::table('kupon_mac')->insert([
            'id' => '31',
            'oranid' => null,
            'kuponid' => '32',
            'userid' => '101',
            'oran' => '1.14',
            'tur' => '1',
            'macid' => '1928678',
            'sonuc' => '0',
            'tarih' => '2025-07-08 01:07:03',
            'canli' => '1',
            'session_id' => null,
            'canlidakika' => '67',
            'skor' => '1-0',
            'iptal' => null,
            'aciklamasi' => 'Tam Zaman',
            'orangrup' => null,
            'evsahibi' => 'Rubio Ñú',
            'deplasman' => 'Deportivo Santaní',
            'mackodu' => '1024102872',
            'sport_id' => '1',
            'matchdate' => '2025-07-07 23:30:00',
            'result' => '0',
            'canliskor' => '1-0',
            'botid' => '61445017',
        ]);
        DB::table('kupon_mac')->insert([
            'id' => '32',
            'oranid' => null,
            'kuponid' => '33',
            'userid' => '101',
            'oran' => '6.5',
            'tur' => 'X',
            'macid' => '1928678',
            'sonuc' => '0',
            'tarih' => '2025-07-08 01:09:13',
            'canli' => '1',
            'session_id' => null,
            'canlidakika' => '67',
            'skor' => '1-0',
            'iptal' => null,
            'aciklamasi' => 'Tam Zaman',
            'orangrup' => null,
            'evsahibi' => 'Rubio Ñú',
            'deplasman' => 'Deportivo Santaní',
            'mackodu' => '1024102872',
            'sport_id' => '1',
            'matchdate' => '2025-07-07 23:30:00',
            'result' => '0',
            'canliskor' => '1-0',
            'botid' => '61445017',
        ]);
        DB::table('kupon_mac')->insert([
            'id' => '33',
            'oranid' => null,
            'kuponid' => '34',
            'userid' => '101',
            'oran' => '2.12',
            'tur' => '2',
            'macid' => '6820483',
            'sonuc' => '0',
            'tarih' => '2025-07-08 01:23:57',
            'canli' => '0',
            'session_id' => null,
            'canlidakika' => null,
            'skor' => null,
            'iptal' => null,
            'aciklamasi' => 'Oklahoma City Thunder Kazanır',
            'orangrup' => null,
            'evsahibi' => 'Philadelphia 76ers',
            'deplasman' => 'Oklahoma City Thunder',
            'mackodu' => '1024143101',
            'sport_id' => '1',
            'matchdate' => '2025-07-08 02:00:00',
            'result' => '0',
            'canliskor' => '',
            'botid' => '0',
        ]);
        DB::table('kupon_mac')->insert([
            'id' => '34',
            'oranid' => null,
            'kuponid' => '35',
            'userid' => '101',
            'oran' => '3.65',
            'tur' => '1-0',
            'macid' => '1928677',
            'sonuc' => '0',
            'tarih' => '2025-07-08 01:34:22',
            'canli' => '1',
            'session_id' => null,
            'canlidakika' => '25',
            'skor' => '0-0',
            'iptal' => null,
            'aciklamasi' => 'Doğru Skor',
            'orangrup' => null,
            'evsahibi' => 'Sportivo Ameliano',
            'deplasman' => 'CA Tembetary',
            'mackodu' => '1022314334',
            'sport_id' => '1',
            'matchdate' => '2025-07-08 00:30:00',
            'result' => '0',
            'canliskor' => '0-0',
            'botid' => '56351897',
        ]);
    }
}
