<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ParayatirTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('parayatir')->insert([
            'id' => '58',
            'uye' => '1',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - havaleeft',
            'islemno' => 'ref-1-1750545252-4597',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-07-04 00:00:52',
            'durum' => '2',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - havaleeft',
        ]);
        DB::table('parayatir')->insert([
            'id' => '57',
            'uye' => '1',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - papara',
            'islemno' => 'ref-1-1750540635-2502',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 01:44:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - papara',
        ]);
        DB::table('parayatir')->insert([
            'id' => '56',
            'uye' => '1',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - paparaiban',
            'islemno' => 'ref-1-1750539672-4927',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 01:28:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - paparaiban',
        ]);
        DB::table('parayatir')->insert([
            'id' => '55',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - havaleeft',
            'islemno' => 'ref-49-1750530662-8994',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-21 22:58:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - havaleeft',
        ]);
        DB::table('parayatir')->insert([
            'id' => '54',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - paparaiban',
            'islemno' => 'ref-49-1750529002-8316',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-21 22:30:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - paparaiban',
        ]);
        DB::table('parayatir')->insert([
            'id' => '53',
            'uye' => '1',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - payco',
            'islemno' => 'ref-1-1750528388-1325',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-21 22:20:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - payco',
        ]);
        DB::table('parayatir')->insert([
            'id' => '52',
            'uye' => '1',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - kripto',
            'islemno' => 'ref-1-1750528069-7314',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-21 22:14:03',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - kripto',
        ]);
        DB::table('parayatir')->insert([
            'id' => '51',
            'uye' => '1',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - paparaiban',
            'islemno' => 'ref-1-1750528061-5258',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-21 22:14:03',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - paparaiban',
        ]);
        DB::table('parayatir')->insert([
            'id' => '50',
            'uye' => '1',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - payfix',
            'islemno' => 'ref-1-1750528004-1896',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-21 22:12:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - payfix',
        ]);
        DB::table('parayatir')->insert([
            'id' => '59',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - havaleeft',
            'islemno' => 'ref-49-1750545410-6061',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 03:02:04',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - havaleeft',
        ]);
        DB::table('parayatir')->insert([
            'id' => '60',
            'uye' => '1',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - papara',
            'islemno' => 'ref-1-1750545418-4362',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 03:02:04',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - papara',
        ]);
        DB::table('parayatir')->insert([
            'id' => '61',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - creditcard',
            'islemno' => 'ref-49-1750545452-9333',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 03:04:05',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - creditcard',
        ]);
        DB::table('parayatir')->insert([
            'id' => '62',
            'uye' => '1',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - mefete',
            'islemno' => 'ref-1-1750545462-5553',
            'miktar' => '100000',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 03:04:05',
            'durum' => '1',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - mefete',
        ]);
        DB::table('parayatir')->insert([
            'id' => '63',
            'uye' => '1001',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - mefete',
            'islemno' => 'ref-1001-1750589696-3876',
            'miktar' => '1000',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarılı',
            'tarih' => '2025-06-22 14:55:03',
            'durum' => '1',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback - mefete',
        ]);
        DB::table('parayatir')->insert([
            'id' => '64',
            'uye' => '1001',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - creditcard',
            'islemno' => 'ref-1001-1750589758-6715',
            'miktar' => '1000',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarılı',
            'tarih' => '2025-06-22 14:56:03',
            'durum' => '1',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback - creditcard',
        ]);
        DB::table('parayatir')->insert([
            'id' => '65',
            'uye' => '1001',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - papara',
            'islemno' => 'ref-1001-1750589796-3597',
            'miktar' => '1000',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarılı',
            'tarih' => '2025-06-22 14:56:41',
            'durum' => '1',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback - papara',
        ]);
        DB::table('parayatir')->insert([
            'id' => '66',
            'uye' => '1001',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - kripto',
            'islemno' => 'ref-1001-1750589771-4494',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 15:22:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - kripto',
        ]);
        DB::table('parayatir')->insert([
            'id' => '67',
            'uye' => '1001',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - havaleeft',
            'islemno' => 'ref-1001-1750595458-4515',
            'miktar' => '1000',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarılı',
            'tarih' => '2025-06-22 16:31:03',
            'durum' => '1',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback - havaleeft',
        ]);
        DB::table('parayatir')->insert([
            'id' => '68',
            'uye' => '1001',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - creditcard',
            'islemno' => 'ref-1001-1750595478-2427',
            'miktar' => '500',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarılı',
            'tarih' => '2025-06-22 16:31:25',
            'durum' => '1',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback - creditcard',
        ]);
        DB::table('parayatir')->insert([
            'id' => '69',
            'uye' => '1001',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - mefete',
            'islemno' => 'ref-1001-1750595567-5121',
            'miktar' => '100',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarılı',
            'tarih' => '2025-06-22 16:32:52',
            'durum' => '1',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback - mefete',
        ]);
        DB::table('parayatir')->insert([
            'id' => '70',
            'uye' => '1001',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - creditcard',
            'islemno' => 'ref-1001-1750599443-5932',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 17:37:30',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - creditcard',
        ]);
        DB::table('parayatir')->insert([
            'id' => '71',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - havalefast',
            'islemno' => 'ref-49-1750600074-4412',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 18:14:03',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - havalefast',
        ]);
        DB::table('parayatir')->insert([
            'id' => '72',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - creditcard',
            'islemno' => 'ref-49-1750601722-1318',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 18:42:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - creditcard',
        ]);
        DB::table('parayatir')->insert([
            'id' => '73',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - papara',
            'islemno' => 'ref-49-1750601731-5691',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 18:42:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - papara',
        ]);
        DB::table('parayatir')->insert([
            'id' => '74',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - paparaiban',
            'islemno' => 'ref-49-1750601727-1829',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 18:42:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - paparaiban',
        ]);
        DB::table('parayatir')->insert([
            'id' => '75',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - havalefast',
            'islemno' => 'ref-49-1750601734-6781',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 18:42:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - havalefast',
        ]);
        DB::table('parayatir')->insert([
            'id' => '76',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - creditcard',
            'islemno' => 'ref-49-1750601750-1386',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 18:42:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - creditcard',
        ]);
        DB::table('parayatir')->insert([
            'id' => '77',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - paparaiban',
            'islemno' => 'ref-49-1750601745-4403',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 18:42:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - paparaiban',
        ]);
        DB::table('parayatir')->insert([
            'id' => '78',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - havalefast',
            'islemno' => 'ref-49-1750601799-4790',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 18:42:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - havalefast',
        ]);
        DB::table('parayatir')->insert([
            'id' => '79',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - paparaiban',
            'islemno' => 'ref-49-1750601803-8100',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 18:42:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - paparaiban',
        ]);
        DB::table('parayatir')->insert([
            'id' => '80',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - havalefast',
            'islemno' => 'ref-49-1750601849-7000',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 18:44:01',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - havalefast',
        ]);
        DB::table('parayatir')->insert([
            'id' => '81',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - havaleeft',
            'islemno' => 'ref-49-1750601925-5376',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 18:44:03',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - havaleeft',
        ]);
        DB::table('parayatir')->insert([
            'id' => '82',
            'uye' => '1001',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - papara',
            'islemno' => 'ref-1001-1750604126-3261',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 19:22:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - papara',
        ]);
        DB::table('parayatir')->insert([
            'id' => '83',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - havaleeft',
            'islemno' => 'ref-49-1750615592-9936',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 22:30:51',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - havaleeft',
        ]);
        DB::table('parayatir')->insert([
            'id' => '84',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - creditcard',
            'islemno' => 'ref-49-1750615546-5879',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 22:32:01',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - creditcard',
        ]);
        DB::table('parayatir')->insert([
            'id' => '85',
            'uye' => '49',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - creditcard',
            'islemno' => 'ref-49-1750615555-6614',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-22 22:32:01',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - creditcard',
        ]);
        DB::table('parayatir')->insert([
            'id' => '86',
            'uye' => '1001',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - payco',
            'islemno' => 'ref-1001-1750627620-7040',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-23 01:52:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - payco',
        ]);
        DB::table('parayatir')->insert([
            'id' => '87',
            'uye' => '1007',
            'adsoyad' => 'Bengisu Türker',
            'tc' => '24391677368',
            'banka' => 'Extra Cüzdan - creditcard',
            'islemno' => 'ref-1007-1750682428-2693',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-23 17:06:02',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - creditcard',
        ]);
        DB::table('parayatir')->insert([
            'id' => '88',
            'uye' => '1001',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - creditcard',
            'islemno' => 'ref-1001-1750895044-5031',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-26 04:10:04',
            'durum' => '1',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - creditcard',
        ]);
        DB::table('parayatir')->insert([
            'id' => '89',
            'uye' => '1001',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - havaleeft',
            'islemno' => 'ref-1001-1750895039-5820',
            'miktar' => '0',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarısız',
            'tarih' => '2025-06-26 04:10:04',
            'durum' => '0',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback Failed - havaleeft',
        ]);
        DB::table('parayatir')->insert([
            'id' => '90',
            'uye' => '1059',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => null,
            'banka' => 'Havale',
            'islemno' => '7846f8053d29bf287ab6bd7f729f486d',
            'miktar' => '20000',
            'tur' => 'Havale',
            'aciklama' => null,
            'tarih' => '2025-06-26 21:07:19',
            'durum' => '1',
            'bonus' => '5',
            'note' => null,
        ]);
        DB::table('parayatir')->insert([
            'id' => '91',
            'uye' => '1059',
            'adsoyad' => 'Yusuf Yalçınkaya',
            'tc' => '13862891952',
            'banka' => 'Extra Cüzdan - havaleeft',
            'islemno' => 'ref-1059-1751063396-6812',
            'miktar' => '100',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarılı',
            'tarih' => '2025-06-28 02:31:40',
            'durum' => '1',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback - havaleeft',
        ]);
        DB::table('parayatir')->insert([
            'id' => '92',
            'uye' => '1001',
            'adsoyad' => 'deneme',
            'tc' => '27227727272',
            'banka' => 'Extra Cüzdan - mefete',
            'islemno' => 'ref-1001-1750595567-5121',
            'miktar' => '10000',
            'tur' => 'Extra Cüzdan',
            'aciklama' => 'Extra Cüzdan ile para yatırma işlemi başarılı',
            'tarih' => '2025-07-04 00:00:52',
            'durum' => '1',
            'bonus' => '0',
            'note' => 'Extra Cüzdan Callback - mefete',
        ]);
    }
}
