<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProvidersTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('providers')->insert([
            'id' => '1',
            'cover' => null,
            'code' => 'iconix',
            'name' => 'iconix',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:43:04',
            'updated_at' => '2025-02-06 18:50:06',
        ]);
        DB::table('providers')->insert([
            'id' => '2',
            'cover' => null,
            'code' => 'pateplay',
            'name' => 'pateplay',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:43:31',
            'updated_at' => '2025-02-06 01:43:31',
        ]);
        DB::table('providers')->insert([
            'id' => '3',
            'cover' => null,
            'code' => 'iconic21',
            'name' => 'iconic21',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:43:36',
            'updated_at' => '2025-02-06 01:43:36',
        ]);
        DB::table('providers')->insert([
            'id' => '4',
            'cover' => null,
            'code' => 'elagames-a',
            'name' => 'elagames-a',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:44:08',
            'updated_at' => '2025-02-06 01:44:08',
        ]);
        DB::table('providers')->insert([
            'id' => '5',
            'cover' => null,
            'code' => 'vivo',
            'name' => 'vivo',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:44:43',
            'updated_at' => '2025-02-06 01:44:43',
        ]);
        DB::table('providers')->insert([
            'id' => '6',
            'cover' => null,
            'code' => 'nolimit',
            'name' => 'nolimit',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:45:19',
            'updated_at' => '2025-02-06 01:45:19',
        ]);
        DB::table('providers')->insert([
            'id' => '7',
            'cover' => null,
            'code' => 'ezugi',
            'name' => 'ezugi',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:47:11',
            'updated_at' => '2025-02-06 01:47:11',
        ]);
        DB::table('providers')->insert([
            'id' => '8',
            'cover' => null,
            'code' => 'ezugiX',
            'name' => 'ezugiX',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:47:17',
            'updated_at' => '2025-02-06 01:47:17',
        ]);
        DB::table('providers')->insert([
            'id' => '9',
            'cover' => null,
            'code' => 'ezugiZ',
            'name' => 'ezugiZ',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:47:20',
            'updated_at' => '2025-02-06 01:47:20',
        ]);
        DB::table('providers')->insert([
            'id' => '10',
            'cover' => null,
            'code' => 'macaw',
            'name' => 'macaw',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:48:35',
            'updated_at' => '2025-02-06 01:48:35',
        ]);
        DB::table('providers')->insert([
            'id' => '11',
            'cover' => null,
            'code' => 'booming',
            'name' => 'booming',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:48:49',
            'updated_at' => '2025-02-06 01:48:49',
        ]);
        DB::table('providers')->insert([
            'id' => '12',
            'cover' => null,
            'code' => 'fancyshoes',
            'name' => 'fancyshoes',
            'image' => null,
            'status' => '0',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:48:50',
            'updated_at' => '2025-02-06 01:48:50',
        ]);
        DB::table('providers')->insert([
            'id' => '13',
            'cover' => null,
            'code' => 'bigpot',
            'name' => 'bigpot',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:48:56',
            'updated_at' => '2025-02-06 01:48:56',
        ]);
        DB::table('providers')->insert([
            'id' => '14',
            'cover' => null,
            'code' => 'airdice',
            'name' => 'airdice',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:50:41',
            'updated_at' => '2025-02-06 01:50:41',
        ]);
        DB::table('providers')->insert([
            'id' => '15',
            'cover' => null,
            'code' => 'armadillostudios',
            'name' => 'armadillostudios',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:50:42',
            'updated_at' => '2025-02-06 01:50:42',
        ]);
        DB::table('providers')->insert([
            'id' => '16',
            'cover' => null,
            'code' => 'betsoft-a',
            'name' => 'betsoft-a',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:51:49',
            'updated_at' => '2025-02-06 01:51:49',
        ]);
        DB::table('providers')->insert([
            'id' => '17',
            'cover' => null,
            'code' => 'adlunam',
            'name' => 'adlunam',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:55:04',
            'updated_at' => '2025-02-06 01:55:04',
        ]);
        DB::table('providers')->insert([
            'id' => '18',
            'cover' => null,
            'code' => 'onegame',
            'name' => 'onegame',
            'image' => null,
            'status' => '0',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:55:05',
            'updated_at' => '2025-02-06 01:55:05',
        ]);
        DB::table('providers')->insert([
            'id' => '19',
            'cover' => null,
            'code' => '1x2gaming',
            'name' => '1x2gaming',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:56:05',
            'updated_at' => '2025-02-06 01:56:05',
        ]);
        DB::table('providers')->insert([
            'id' => '20',
            'cover' => null,
            'code' => 'bigtimegaming-a',
            'name' => 'bigtimegaming-a',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:56:54',
            'updated_at' => '2025-02-06 01:56:54',
        ]);
        DB::table('providers')->insert([
            'id' => '21',
            'cover' => null,
            'code' => 'prospectgaming',
            'name' => 'prospectgaming',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:57:36',
            'updated_at' => '2025-02-06 01:57:36',
        ]);
        DB::table('providers')->insert([
            'id' => '22',
            'cover' => null,
            'code' => 'jvl',
            'name' => 'jvl',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:57:38',
            'updated_at' => '2025-02-06 01:57:38',
        ]);
        DB::table('providers')->insert([
            'id' => '23',
            'cover' => null,
            'code' => 'irondogPP',
            'name' => 'irondogPP',
            'image' => null,
            'status' => '0',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:57:53',
            'updated_at' => '2025-02-06 01:57:53',
        ]);
        DB::table('providers')->insert([
            'id' => '24',
            'cover' => null,
            'code' => 'irondogP',
            'name' => 'irondogP',
            'image' => null,
            'status' => '0',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:57:56',
            'updated_at' => '2025-02-06 01:57:56',
        ]);
        DB::table('providers')->insert([
            'id' => '25',
            'cover' => null,
            'code' => '100hp',
            'name' => '100hp',
            'image' => null,
            'status' => '0',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:58:21',
            'updated_at' => '2025-02-06 01:58:21',
        ]);
        DB::table('providers')->insert([
            'id' => '26',
            'cover' => null,
            'code' => 'only-play',
            'name' => 'only-play',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 01:58:28',
            'updated_at' => '2025-02-06 01:58:28',
        ]);
        DB::table('providers')->insert([
            'id' => '27',
            'cover' => null,
            'code' => 'espressogames-a',
            'name' => 'espressogames-a',
            'image' => null,
            'status' => '0',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 02:00:21',
            'updated_at' => '2025-02-06 02:00:21',
        ]);
        DB::table('providers')->insert([
            'id' => '28',
            'cover' => null,
            'code' => 'sagaming',
            'name' => 'sagaming',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 02:01:59',
            'updated_at' => '2025-02-06 02:01:59',
        ]);
        DB::table('providers')->insert([
            'id' => '29',
            'cover' => null,
            'code' => 'evolutionWCX',
            'name' => 'evolutionWCX',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 02:02:34',
            'updated_at' => '2025-02-06 02:02:34',
        ]);
        DB::table('providers')->insert([
            'id' => '30',
            'cover' => null,
            'code' => 'evolutionWC',
            'name' => 'evolutionWC',
            'image' => null,
            'status' => '1',
            'rtp' => '90',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 02:02:35',
            'updated_at' => '2025-02-06 02:02:35',
        ]);
        DB::table('providers')->insert([
            'id' => '31',
            'cover' => null,
            'code' => 'evolutionWCLS',
            'name' => 'evolutionWCLS',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '32',
            'cover' => null,
            'code' => 'evolutionWCHS',
            'name' => 'evolutionWCHS',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '33',
            'cover' => null,
            'code' => 'evolutionWCY',
            'name' => 'evolutionWCY',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '34',
            'cover' => null,
            'code' => 'egtdigital',
            'name' => 'egtdigital',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '35',
            'cover' => null,
            'code' => 'fazi',
            'name' => 'fazi',
            'image' => null,
            'status' => '1',
            'rtp' => '83',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '36',
            'cover' => null,
            'code' => 'redstone',
            'name' => 'redstone',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '37',
            'cover' => null,
            'code' => 'tiptop',
            'name' => 'tiptop',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '38',
            'cover' => null,
            'code' => 'amigogaming',
            'name' => 'amigogaming',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '39',
            'cover' => null,
            'code' => 'tada',
            'name' => 'tada',
            'image' => null,
            'status' => '1',
            'rtp' => '97',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '40',
            'cover' => null,
            'code' => 'apparat',
            'name' => 'apparat',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '41',
            'cover' => null,
            'code' => 'barbara-bang',
            'name' => 'barbara-bang',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '42',
            'cover' => null,
            'code' => 'kagaming',
            'name' => 'kagaming',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '43',
            'cover' => null,
            'code' => 'netgame',
            'name' => 'netgame',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '44',
            'cover' => null,
            'code' => 'bitville',
            'name' => 'bitville',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '45',
            'cover' => null,
            'code' => 'bgaming',
            'name' => 'bgaming',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '46',
            'cover' => null,
            'code' => 'bgamingP',
            'name' => 'bgamingP',
            'image' => null,
            'status' => '0',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '47',
            'cover' => null,
            'code' => 'rubyplay',
            'name' => 'rubyplay',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '48',
            'cover' => null,
            'code' => 'aviator',
            'name' => 'aviator',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '49',
            'cover' => null,
            'code' => 'spribe',
            'name' => 'spribe',
            'image' => null,
            'status' => '1',
            'rtp' => '97',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '50',
            'cover' => null,
            'code' => 'yggdrasil',
            'name' => 'yggdrasil',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '51',
            'cover' => null,
            'code' => 'yoloplay-a',
            'name' => 'yoloplay-a',
            'image' => null,
            'status' => '0',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '52',
            'cover' => null,
            'code' => 'evoplay',
            'name' => 'evoplay',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '53',
            'cover' => null,
            'code' => 'slotopia',
            'name' => 'slotopia',
            'image' => null,
            'status' => '0',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '54',
            'cover' => null,
            'code' => 'creedz-vgs',
            'name' => 'creedz-vgs',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '55',
            'cover' => null,
            'code' => 'creedz',
            'name' => 'creedz',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '56',
            'cover' => null,
            'code' => 'creedz-bj',
            'name' => 'creedz-bj',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '57',
            'cover' => null,
            'code' => 'amusnet',
            'name' => 'amusnet',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '58',
            'cover' => null,
            'code' => 'livegames',
            'name' => 'livegames',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '59',
            'cover' => null,
            'code' => 'habanero',
            'name' => 'habanero',
            'image' => null,
            'status' => '1',
            'rtp' => '94',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '60',
            'cover' => null,
            'code' => 'pragmatic',
            'name' => 'pragmatic',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '61',
            'cover' => null,
            'code' => 'pragmatic',
            'name' => 'pragmatic',
            'image' => null,
            'status' => '1',
            'rtp' => '74',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '62',
            'cover' => null,
            'code' => 'pragmatic',
            'name' => 'pragmatic',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '63',
            'cover' => null,
            'code' => 'pragmatic',
            'name' => 'pragmatic',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '64',
            'cover' => null,
            'code' => 'pragmatic',
            'name' => 'pragmatic',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '65',
            'cover' => null,
            'code' => 'endorphina',
            'name' => 'endorphina',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '66',
            'cover' => null,
            'code' => 'skywind',
            'name' => 'skywind',
            'image' => null,
            'status' => '1',
            'rtp' => '97',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '67',
            'cover' => null,
            'code' => 'skywind-live',
            'name' => 'skywind-live',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '68',
            'cover' => null,
            'code' => 'skywind-bj',
            'name' => 'skywind-bj',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:02',
            'updated_at' => '2025-02-06 13:35:02',
        ]);
        DB::table('providers')->insert([
            'id' => '69',
            'cover' => null,
            'code' => 'netentWC',
            'name' => 'netentWC',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '70',
            'cover' => null,
            'code' => 'redtiger',
            'name' => 'redtiger',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '71',
            'cover' => null,
            'code' => 'caletagaming',
            'name' => 'caletagaming',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '72',
            'cover' => null,
            'code' => 'absolute',
            'name' => 'absolute',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '73',
            'cover' => null,
            'code' => '7-mojos',
            'name' => '7-mojos',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '74',
            'cover' => null,
            'code' => '7-mojos-slots',
            'name' => '7-mojos-slots',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '75',
            'cover' => null,
            'code' => 'altente',
            'name' => 'altente',
            'image' => null,
            'status' => '0',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '76',
            'cover' => null,
            'code' => 'religa',
            'name' => 'religa',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '77',
            'cover' => null,
            'code' => 'wazdan',
            'name' => 'wazdan',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '78',
            'cover' => null,
            'code' => 'bfgames',
            'name' => 'bfgames',
            'image' => null,
            'status' => '1',
            'rtp' => '94',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '79',
            'cover' => null,
            'code' => 'hacksaw',
            'name' => 'hacksaw',
            'image' => null,
            'status' => '1',
            'rtp' => '77',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '80',
            'cover' => null,
            'code' => 'backseat',
            'name' => 'backseat',
            'image' => null,
            'status' => '1',
            'rtp' => '94',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '81',
            'cover' => null,
            'code' => 'bullshark',
            'name' => 'bullshark',
            'image' => null,
            'status' => '1',
            'rtp' => '94',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '82',
            'cover' => null,
            'code' => 'popok',
            'name' => 'popok',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '83',
            'cover' => null,
            'code' => 'popok',
            'name' => 'popok',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '84',
            'cover' => null,
            'code' => 'platipus',
            'name' => 'platipus',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '85',
            'cover' => null,
            'code' => 'mancala',
            'name' => 'mancala',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '86',
            'cover' => null,
            'code' => 'goldenrace',
            'name' => 'goldenrace',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '87',
            'cover' => null,
            'code' => 'retrogames',
            'name' => 'retrogames',
            'image' => null,
            'status' => '1',
            'rtp' => '94',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '88',
            'cover' => null,
            'code' => 'spinomenal',
            'name' => 'spinomenal',
            'image' => null,
            'status' => '1',
            'rtp' => '97',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '89',
            'cover' => null,
            'code' => 'fils',
            'name' => 'fils',
            'image' => null,
            'status' => '0',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '90',
            'cover' => null,
            'code' => 'liw',
            'name' => 'liw',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '91',
            'cover' => null,
            'code' => 'tvbet',
            'name' => 'tvbet',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '92',
            'cover' => null,
            'code' => 'jetx',
            'name' => 'jetx',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '93',
            'cover' => null,
            'code' => 'smartsoft',
            'name' => 'smartsoft',
            'image' => null,
            'status' => '1',
            'rtp' => '97',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '94',
            'cover' => null,
            'code' => 'onetouch',
            'name' => 'onetouch',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '95',
            'cover' => null,
            'code' => 'onetouch-live',
            'name' => 'onetouch-live',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '96',
            'cover' => null,
            'code' => 'spearhead',
            'name' => 'spearhead',
            'image' => null,
            'status' => '1',
            'rtp' => '97',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '97',
            'cover' => null,
            'code' => 'spearhead',
            'name' => 'spearhead',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '98',
            'cover' => null,
            'code' => 'pgsoft',
            'name' => 'pgsoft',
            'image' => null,
            'status' => '1',
            'rtp' => '97',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '99',
            'cover' => null,
            'code' => 'platingaming',
            'name' => 'platingaming',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '100',
            'cover' => null,
            'code' => '7777',
            'name' => '7777',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '101',
            'cover' => null,
            'code' => 'micro-gaming',
            'name' => 'micro-gaming',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '102',
            'cover' => null,
            'code' => 'micro-gaming-live',
            'name' => 'micro-gaming-live',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '103',
            'cover' => null,
            'code' => 'gamzix',
            'name' => 'gamzix',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '104',
            'cover' => null,
            'code' => 'redrake',
            'name' => 'redrake',
            'image' => null,
            'status' => '1',
            'rtp' => '100',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '105',
            'cover' => null,
            'code' => 'aviatrix',
            'name' => 'aviatrix',
            'image' => null,
            'status' => '1',
            'rtp' => '97',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '106',
            'cover' => null,
            'code' => 'irondog',
            'name' => 'irondog',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '107',
            'cover' => null,
            'code' => 'galaxsys',
            'name' => 'galaxsys',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '108',
            'cover' => null,
            'code' => 'ctinteractive',
            'name' => 'ctinteractive',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '109',
            'cover' => null,
            'code' => '3oaks',
            'name' => '3oaks',
            'image' => null,
            'status' => '0',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '110',
            'cover' => null,
            'code' => '3oaksP',
            'name' => '3oaksP',
            'image' => null,
            'status' => '0',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '111',
            'cover' => null,
            'code' => 'turbo-games',
            'name' => 'turbo-games',
            'image' => null,
            'status' => '1',
            'rtp' => '94',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '112',
            'cover' => null,
            'code' => 'novo-matic',
            'name' => 'novo-matic',
            'image' => null,
            'status' => '1',
            'rtp' => '92',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '113',
            'cover' => null,
            'code' => 'play-son',
            'name' => 'play-son',
            'image' => null,
            'status' => '1',
            'rtp' => '96',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
        DB::table('providers')->insert([
            'id' => '114',
            'cover' => null,
            'code' => 'play-son',
            'name' => 'play-son',
            'image' => null,
            'status' => '1',
            'rtp' => '95',
            'views' => '1',
            'distribution' => 'drakon',
            'created_at' => '2025-02-06 13:35:03',
            'updated_at' => '2025-02-06 13:35:03',
        ]);
    }
}
