<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TransactionsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('transactions')->insert([
            'id' => '163',
            'user_id' => '101',
            'type' => 'win',
            'amount' => '100.55',
            'created_at' => '2025-07-6 20:39:14',
            'gamename' => '',
            'transactionid' => '37357652772',
            'gameid' => '23724',
            'game_name' => null,
            'session_id' => 'eyJpdiI6Ild4OHo5QzFISkNlbHQ3VTRQRk9KbXc9PSIsInZhbH',
            'description' => null,
            'additional_data' => null,
            'win_method' => null,
            'multiplier' => null,
            'spin_number' => null,
            'free_spins' => null,
        ]);
        DB::table('transactions')->insert([
            'id' => '164',
            'user_id' => '1059',
            'type' => 'bet',
            'amount' => '10.00',
            'created_at' => '2025-06-28 01:33:50',
            'gamename' => '',
            'transactionid' => '37429154031',
            'gameid' => '23724',
            'game_name' => null,
            'session_id' => 'eyJpdiI6IjFlOEVOSFIwSjF3RXBzcENHNVJYaWc9PSIsInZhbH',
            'description' => null,
            'additional_data' => null,
            'win_method' => null,
            'multiplier' => null,
            'spin_number' => null,
            'free_spins' => null,
        ]);
        DB::table('transactions')->insert([
            'id' => '165',
            'user_id' => '101',
            'type' => 'win',
            'amount' => '500.00',
            'created_at' => '2025-07-6 20:39:14',
            'gamename' => '',
            'transactionid' => '37357652772',
            'gameid' => '23724',
            'game_name' => null,
            'session_id' => 'eyJpdiI6Ild4OHo5QzFISkNlbHQ3VTRQRk9KbXc9PSIsInZhbH',
            'description' => null,
            'additional_data' => null,
            'win_method' => null,
            'multiplier' => null,
            'spin_number' => null,
            'free_spins' => null,
        ]);
        DB::table('transactions')->insert([
            'id' => '166',
            'user_id' => '101',
            'type' => 'win',
            'amount' => '100.55',
            'created_at' => '2025-07-6 20:39:14',
            'gamename' => '',
            'transactionid' => '37357652772',
            'gameid' => '23724',
            'game_name' => null,
            'session_id' => 'eyJpdiI6Ild4OHo5QzFISkNlbHQ3VTRQRk9KbXc9PSIsInZhbH',
            'description' => null,
            'additional_data' => null,
            'win_method' => null,
            'multiplier' => null,
            'spin_number' => null,
            'free_spins' => null,
        ]);
        DB::table('transactions')->insert([
            'id' => '167',
            'user_id' => '101',
            'type' => 'bet',
            'amount' => '500.00',
            'created_at' => '2025-07-6 20:39:14',
            'gamename' => '',
            'transactionid' => '37357652772',
            'gameid' => '23724',
            'game_name' => null,
            'session_id' => 'eyJpdiI6Ild4OHo5QzFISkNlbHQ3VTRQRk9KbXc9PSIsInZhbH',
            'description' => null,
            'additional_data' => null,
            'win_method' => null,
            'multiplier' => null,
            'spin_number' => null,
            'free_spins' => null,
        ]);
        DB::table('transactions')->insert([
            'id' => '174',
            'user_id' => '101',
            'type' => 'bet',
            'amount' => '1.00',
            'created_at' => '2025-07-08 04:53:15',
            'gamename' => '',
            'transactionid' => '37821045368',
            'gameid' => '23002',
            'game_name' => null,
            'session_id' => 'eyJpdiI6IlFxNTVscWRzNU4rTEJUOFpMYnJvbXc9PSIsInZhbH',
            'description' => null,
            'additional_data' => null,
            'win_method' => null,
            'multiplier' => null,
            'spin_number' => null,
            'free_spins' => null,
        ]);
        DB::table('transactions')->insert([
            'id' => '175',
            'user_id' => '101',
            'type' => 'bet',
            'amount' => '1.00',
            'created_at' => '2025-07-08 05:06:31',
            'gamename' => '',
            'transactionid' => '37821514905',
            'gameid' => '23002',
            'game_name' => null,
            'session_id' => 'eyJpdiI6InBvN3BvTWk2TTA5ckFWeUc3WStNY1E9PSIsInZhbH',
            'description' => null,
            'additional_data' => null,
            'win_method' => null,
            'multiplier' => null,
            'spin_number' => null,
            'free_spins' => null,
        ]);
        DB::table('transactions')->insert([
            'id' => '176',
            'user_id' => '101',
            'type' => 'bet',
            'amount' => '1.00',
            'created_at' => '2025-07-08 05:07:02',
            'gamename' => '',
            'transactionid' => '37821533789',
            'gameid' => '23002',
            'game_name' => 'Gates of Olympus',
            'session_id' => 'eyJpdiI6InBvN3BvTWk2TTA5ckFWeUc3WStNY1E9PSIsInZhbH',
            'description' => 'Bet placed on Gates of Olympus - Amount: 1 TL',
            'additional_data' => '{\"spin_number\":null,\"free_spins\":null,\"bet_per_line\":null,\"lines\":null,\"total_bet\":1}',
            'win_method' => null,
            'multiplier' => null,
            'spin_number' => null,
            'free_spins' => null,
        ]);
        DB::table('transactions')->insert([
            'id' => '177',
            'user_id' => '101',
            'type' => 'bet',
            'amount' => '1.00',
            'created_at' => '2025-07-08 05:07:38',
            'gamename' => '',
            'transactionid' => '37821554572',
            'gameid' => '23002',
            'game_name' => 'Gates of Olympus',
            'session_id' => 'eyJpdiI6InBvN3BvTWk2TTA5ckFWeUc3WStNY1E9PSIsInZhbH',
            'description' => 'Bet placed on Gates of Olympus - Amount: 1 TL',
            'additional_data' => '{\"spin_number\":null,\"free_spins\":null,\"bet_per_line\":null,\"lines\":null,\"total_bet\":1}',
            'win_method' => null,
            'multiplier' => null,
            'spin_number' => null,
            'free_spins' => null,
        ]);
        DB::table('transactions')->insert([
            'id' => '178',
            'user_id' => '101',
            'type' => 'bet',
            'amount' => '1.00',
            'created_at' => '2025-07-08 05:07:39',
            'gamename' => '',
            'transactionid' => '37821555391',
            'gameid' => '23002',
            'game_name' => 'Gates of Olympus',
            'session_id' => 'eyJpdiI6InBvN3BvTWk2TTA5ckFWeUc3WStNY1E9PSIsInZhbH',
            'description' => 'Bet placed on Gates of Olympus - Amount: 1 TL',
            'additional_data' => '{\"spin_number\":null,\"free_spins\":null,\"bet_per_line\":null,\"lines\":null,\"total_bet\":1}',
            'win_method' => null,
            'multiplier' => null,
            'spin_number' => null,
            'free_spins' => null,
        ]);
        DB::table('transactions')->insert([
            'id' => '179',
            'user_id' => '101',
            'type' => 'bet',
            'amount' => '1.00',
            'created_at' => '2025-07-08 05:07:41',
            'gamename' => '',
            'transactionid' => '37821556146',
            'gameid' => '23002',
            'game_name' => 'Gates of Olympus',
            'session_id' => 'eyJpdiI6InBvN3BvTWk2TTA5ckFWeUc3WStNY1E9PSIsInZhbH',
            'description' => 'Bet placed on Gates of Olympus - Amount: 1 TL',
            'additional_data' => '{\"spin_number\":null,\"free_spins\":null,\"bet_per_line\":null,\"lines\":null,\"total_bet\":1}',
            'win_method' => null,
            'multiplier' => null,
            'spin_number' => null,
            'free_spins' => null,
        ]);
        DB::table('transactions')->insert([
            'id' => '180',
            'user_id' => '101',
            'type' => 'bet',
            'amount' => '1.00',
            'created_at' => '2025-07-08 05:07:43',
            'gamename' => '',
            'transactionid' => '37821557478',
            'gameid' => '23002',
            'game_name' => 'Gates of Olympus',
            'session_id' => 'eyJpdiI6InBvN3BvTWk2TTA5ckFWeUc3WStNY1E9PSIsInZhbH',
            'description' => 'Bet placed on Gates of Olympus - Amount: 1 TL',
            'additional_data' => '{\"spin_number\":null,\"free_spins\":null,\"bet_per_line\":null,\"lines\":null,\"total_bet\":1}',
            'win_method' => null,
            'multiplier' => null,
            'spin_number' => null,
            'free_spins' => null,
        ]);
        DB::table('transactions')->insert([
            'id' => '181',
            'user_id' => '101',
            'type' => 'bet',
            'amount' => '1.00',
            'created_at' => '2025-07-08 05:07:44',
            'gamename' => '',
            'transactionid' => '37821558304',
            'gameid' => '23002',
            'game_name' => 'Gates of Olympus',
            'session_id' => 'eyJpdiI6InBvN3BvTWk2TTA5ckFWeUc3WStNY1E9PSIsInZhbH',
            'description' => 'Bet placed on Gates of Olympus - Amount: 1 TL',
            'additional_data' => '{\"spin_number\":null,\"free_spins\":null,\"bet_per_line\":null,\"lines\":null,\"total_bet\":1}',
            'win_method' => null,
            'multiplier' => null,
            'spin_number' => null,
            'free_spins' => null,
        ]);
        DB::table('transactions')->insert([
            'id' => '182',
            'user_id' => '101',
            'type' => 'win',
            'amount' => '0.50',
            'created_at' => '2025-07-08 05:07:47',
            'gamename' => '',
            'transactionid' => '37821560025',
            'gameid' => '23002',
            'game_name' => 'Gates of Olympus',
            'session_id' => 'eyJpdiI6InBvN3BvTWk2TTA5ckFWeUc3WStNY1E9PSIsInZhbH',
            'description' => 'Win on Gates of Olympus - Amount: 0.5 TL - Method: Normal Win',
            'additional_data' => '{\"spin_number\":null,\"free_spins\":null,\"multiplier\":null,\"win_lines\":null,\"bonus_game\":false,\"jackpot\":false,\"win_method\":\"Normal Win\"}',
            'win_method' => 'Normal Win',
            'multiplier' => null,
            'spin_number' => null,
            'free_spins' => null,
        ]);
    }
}
